# Generated by Django 2.1.4 on 2019-05-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cousine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('classification_column', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CousineTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=250)),
                ('cousine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Cousine')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Meal name', max_length=256)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('day', models.DateField()),
                ('cousine_set', models.BooleanField(blank=True, default=False, null=True)),
                ('automatic_classification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classification.DailyMenuClassification')),
                ('cousine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.Cousine')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenuTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.DailyMenu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=256)),
                ('menu_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('address', models.CharField(blank=True, default=None, help_text='Restaurant address', max_length=256, null=True)),
                ('rating', models.IntegerField(default=0, help_text='Automatically computed rating, based on menu rating')),
                ('gps_lat', models.FloatField(blank=True, default=None, null=True)),
                ('gps_lng', models.FloatField(blank=True, default=None, null=True)),
                ('cousine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.Cousine')),
            ],
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu', to='restaurants.Restaurant'),
        ),
    ]
