# Generated by Django 2.1.4 on 2019-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='classification_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
