# Generated by Django 2.1.4 on 2019-05-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('recommendation_class', models.CharField(max_length=250)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Recommender'),
        ),
    ]
