# Generated by Django 2.1.4 on 2019-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190505_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommender',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
