# Generated by Django 2.1.4 on 2019-05-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190506_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendationlocation',
            name='recommendation_type',
            field=models.CharField(default='restaurants', help_text='Use position or visited restaurants?', max_length=64),
        ),
    ]
