version: '3'
services:

  postgresql:
    build:
      context: ./
      dockerfile: ./Dockerfile_db
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: heslo
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  elasticsearch:
    build:
      context: ./
      dockerfile: ./Dockerfile_elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=atchutna-elasticsearch
      - bootstrap.memory_lock=false
      - network.publish_host=0.0.0.0
      - discovery.type=single-node
      #      - ELASTIC_PASSWORD=heslo
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    container_name: daily_menu_api
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./daily_menu:/usr/src/daily_menu
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - elasticsearch



#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
#    container_name: elasticsearch2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata2:/usr/share/elasticsearch/data
#    networks:
#      - esnet

volumes:
  #  postgres_data:
  esdata1:
    driver: local
#  esdata2:
#    driver: local
#
#networks:
#  esnet:
#  web: