# Generated by Django 2.1.4 on 2019-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenuClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.FloatField(blank=True, default=None, null=True)),
                ('vegan', models.FloatField(blank=True, default=None, null=True)),
                ('meat', models.FloatField(blank=True, default=None, null=True)),
                ('beef', models.FloatField(blank=True, default=None, null=True)),
                ('pork', models.FloatField(blank=True, default=None, null=True)),
                ('venison', models.FloatField(blank=True, default=None, null=True)),
                ('fish', models.FloatField(blank=True, default=None, null=True)),
                ('poultry', models.FloatField(blank=True, default=None, null=True)),
                ('seafood', models.FloatField(blank=True, default=None, null=True)),
                ('pasta', models.FloatField(blank=True, default=None, null=True)),
                ('tofu', models.FloatField(blank=True, default=None, null=True)),
                ('potatoes', models.FloatField(blank=True, default=None, null=True)),
                ('rice', models.FloatField(blank=True, default=None, null=True)),
                ('cheese', models.FloatField(blank=True, default=None, null=True)),
                ('mushrooms', models.FloatField(blank=True, default=None, null=True)),
                ('indian', models.FloatField(blank=True, default=None, null=True)),
                ('vietnamese', models.FloatField(blank=True, default=None, null=True)),
                ('mexican', models.FloatField(blank=True, default=None, null=True)),
                ('czech', models.FloatField(blank=True, default=None, null=True)),
                ('american', models.FloatField(blank=True, default=None, null=True)),
                ('chinese', models.FloatField(blank=True, default=None, null=True)),
                ('italian', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotMealTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('is_significant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagGeneralization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=250)),
                ('extra_tag', models.TextField(max_length=250)),
                ('tag_canonical', models.TextField(blank=True, max_length=250, null=True)),
                ('extra_tag_canonical', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.FloatField(blank=True, default=None, null=True)),
                ('vegan', models.FloatField(blank=True, default=None, null=True)),
                ('meat', models.FloatField(blank=True, default=None, null=True)),
                ('beef', models.FloatField(blank=True, default=None, null=True)),
                ('pork', models.FloatField(blank=True, default=None, null=True)),
                ('venison', models.FloatField(blank=True, default=None, null=True)),
                ('fish', models.FloatField(blank=True, default=None, null=True)),
                ('poultry', models.FloatField(blank=True, default=None, null=True)),
                ('seafood', models.FloatField(blank=True, default=None, null=True)),
                ('pasta', models.FloatField(blank=True, default=None, null=True)),
                ('tofu', models.FloatField(blank=True, default=None, null=True)),
                ('potatoes', models.FloatField(blank=True, default=None, null=True)),
                ('rice', models.FloatField(blank=True, default=None, null=True)),
                ('cheese', models.FloatField(blank=True, default=None, null=True)),
                ('mushrooms', models.FloatField(blank=True, default=None, null=True)),
                ('indian', models.FloatField(blank=True, default=None, null=True)),
                ('vietnamese', models.FloatField(blank=True, default=None, null=True)),
                ('mexican', models.FloatField(blank=True, default=None, null=True)),
                ('czech', models.FloatField(blank=True, default=None, null=True)),
                ('american', models.FloatField(blank=True, default=None, null=True)),
                ('chinese', models.FloatField(blank=True, default=None, null=True)),
                ('italian', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserManualClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.FloatField(blank=True, default=None, null=True)),
                ('vegan', models.FloatField(blank=True, default=None, null=True)),
                ('meat', models.FloatField(blank=True, default=None, null=True)),
                ('beef', models.FloatField(blank=True, default=None, null=True)),
                ('pork', models.FloatField(blank=True, default=None, null=True)),
                ('venison', models.FloatField(blank=True, default=None, null=True)),
                ('fish', models.FloatField(blank=True, default=None, null=True)),
                ('poultry', models.FloatField(blank=True, default=None, null=True)),
                ('seafood', models.FloatField(blank=True, default=None, null=True)),
                ('pasta', models.FloatField(blank=True, default=None, null=True)),
                ('tofu', models.FloatField(blank=True, default=None, null=True)),
                ('potatoes', models.FloatField(blank=True, default=None, null=True)),
                ('rice', models.FloatField(blank=True, default=None, null=True)),
                ('cheese', models.FloatField(blank=True, default=None, null=True)),
                ('mushrooms', models.FloatField(blank=True, default=None, null=True)),
                ('indian', models.FloatField(blank=True, default=None, null=True)),
                ('vietnamese', models.FloatField(blank=True, default=None, null=True)),
                ('mexican', models.FloatField(blank=True, default=None, null=True)),
                ('czech', models.FloatField(blank=True, default=None, null=True)),
                ('american', models.FloatField(blank=True, default=None, null=True)),
                ('chinese', models.FloatField(blank=True, default=None, null=True)),
                ('italian', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
