from django.core.management import BaseCommand
from datetime import datetime

from crawler.models import RestaurantScraperConfig
from restaurants.models import Restaurant


class Command(BaseCommand):
    help = 'Scrape recipes websites and save new recipes'

    def handle(self, *args, **kwargs):
        data = (('Tankovna Karlín', 'https://www.zomato.com/praha/tankovna-karlín-karlín-praha-8/menu', '18057566'),
                ('Globus restaurace', 'https://www.zomato.com/praha/globus-restaurace-karlín-praha-8/menu', '18257507'),
                ('U Zábranských', 'https://www.zomato.com/praha/u-zábranských-karlín-praha-8/menu', '16505936'),
                ('Peter\'s Burger Pub', 'https://www.zomato.com/praha/peters-burger-pub-karlín-praha-8/menu',
                 '16506740'),
                ('Motoburger', 'https://www.zomato.com/praha/motoburger-holešovice-praha-7/menu', '16506093'),
                ('Lokál', 'https://www.zomato.com/praha/lokál-staré-město-praha-1/menu', '16506246'),
                ('Naše maso', 'https://www.zomato.com/praha/naše-maso-staré-město-praha-1/menu', '16521490'),
                ('Marina Ristorante', 'https://www.zomato.com/praha/marina-ristorante-staré-město-praha-1/menu',
                 '16516177'),
                ('Café Louvre', 'https://www.zomato.com/praha/café-louvre-nové-město-praha-1/menu', '16505933'),
                ('Meat & Greet', 'https://www.zomato.com/praha/meat-greet-nové-město-praha-1/menu', '16522037'),
                ('Oblaca', 'https://www.zomato.com/oblaca/menu', '16506767'),
                ('Café Imperial', 'https://www.zomato.com/praha/café-imperial-nové-město-praha-1/menu', '16507072'),
                ('Mincovna', 'https://www.zomato.com/praha/mincovna-staré-město-praha-1/menu', '16507496'),
                ('Dish fine burger bistro',
                 'https://www.zomato.com/praha/dish-fine-burger-bistro-vinohrady-praha-2/menu', '16506649'),
                ('Pizza Nuova', 'https://www.zomato.com/praha/pizza-nuova-staré-město-praha-1/menu', '16506006'),
                (
                    'Marthy\'s Kitchen', 'https://www.zomato.com/praha/marthys-kitchen-vinohrady-praha-2/menu',
                    '16512484'),
                ('Cacao', 'https://www.zomato.com/cacaoprague/menu', '16507326'),
                ('Tom\'s Burger restaurant',
                 'https://www.zomato.com/praha/toms-burger-restaurant-vinohrady-praha-2/menu', '16521732'),
                ('Nejen Bistro', 'https://www.zomato.com/praha/nejen-bistro-karlín-praha-8/menu', '17887543'),
                ('Coa', 'https://www.zomato.com/praha/coa-staré-město-praha-1/menu', '16506815'),
                ('Kredenc', 'https://www.zomato.com/praha/kredenc-žižkov-praha-3/menu', '16507522'),
                ('Gao Den', 'https://www.zomato.com/praha/gao-den-stodůlky-praha-5/menu', '16507573'),
                ('Kravín', 'https://www.zomato.com/praha/kravín-vinohrady-praha-2/menu', '16506957'),
                ('U provaznice', 'https://www.zomato.com/praha/u-provaznice-staré-město-praha-1/menu', '16506342'),
                ('Šenkovna', 'https://www.zomato.com/praha/šenkovna-nové-město-praha-2/menu', '16505917'),
                ('Wine food market', 'https://www.zomato.com/praha/wine-food-market-smíchov-praha-5/menu', '16509899'),
                ('Deli Viet', 'https://www.zomato.com/praha/deli-viet-nové-město-praha-1/menu', '16521499'),
                ('Prostor', 'https://www.zomato.com/praha/prostor-smíchov-praha-5/menu', '16507599'),
                ('Hybernia', 'https://www.zomato.com/praha/hybernia-nové-město-praha-1/menu', '16506886'),
                ('Odpočívadlo', 'https://www.zomato.com/praha/odpočívadlo-smíchov-praha-5/menu', '16505924'),
                ('T-Anker', 'https://www.zomato.com/praha/t-anker-staré-město-praha-1/menu', '16506904'),
                ('Lidová jídelna', 'https://www.zomato.com/praha/lidová-jídelna-nové-město-praha-1/menu', '16506215'),
                ('Nominanza', 'https://www.zomato.com/praha/nominanza-žižkov-praha-3/menu', '16513818'),
                ('T.G.I. Friday\'s', 'https://www.zomato.com/praha/t-g-i-fridays-1-smíchov-praha-5/menu', '16506064'),
                ('Husinec', 'https://www.zomato.com/praha/husinec-nové-město-praha-1/menu', '16521942'),
                ('Jiná krajina', 'https://www.zomato.com/praha/jiná-krajina-nové-město-praha-1/menu', '16506026'),
                ('Le Burger', 'https://www.zomato.com/leburger/menu', '16521794'),
                ('Lavande', 'https://www.zomato.com/lavande/menu', '16507605'),
                ('Lavička', 'https://www.zomato.com/praha/lavička-žižkov-praha-3/menu', '16506844'),
                ('Etnosvět', 'https://www.zomato.com/praha/etnosvět-nové-město-praha-2/menu', '17978808'),
                ('Pasta Fresca', 'https://www.zomato.com/praha/pasta-fresca-staré-město-praha-1/menu', '16506538'),
                ('Pivovar Lužiny', 'https://www.zomato.com/praha/pivovar-lužiny-stodůlky-praha-5/menu', '16507520'),
                ('Gate Restaurant', 'https://www.zomato.com/praha/gate-restaurant-karlín-praha-8/menu', '16506013'),
                ('Plevel', 'https://www.zomato.com/praha/plevel-vršovice-praha-10/menu', '16506839'),
                ('Lokál U Bílé Kuželky', 'https://www.zomato.com/praha/lokál-u-bílé-kuželky-malá-strana-praha-1/menu',
                 '16506245'),
                ('Lokál Hamburk', 'https://www.zomato.com/praha/lokál-hamburk-karlín-praha-8/menu', '16507478'),
                ('Pizzerie Václavka', 'https://www.zomato.com/praha/pizzerie-václavka-nové-město-praha-1/menu',
                 '16506657'),
                ('Hoffa', 'https://www.zomato.com/praha/hoffa-nové-město-praha-1/menu', '16506782'),
                ('EMA espresso bar', 'https://www.zomato.com/praha/ema-espresso-bar-nové-město-praha-1/menu',
                 '16509309'),
                ('Lehká hlava', 'https://www.zomato.com/praha/lehká-hlava-staré-město-praha-1/menu', '16507457'),
                ('Radegastovna Perón', 'https://www.zomato.com/praha/radegastovna-perón-smíchov-praha-5/menu',
                 '16506659'),
                ('Pastař', 'https://www.zomato.com/pastar/menu', '16521550'),
                ('Fiesta', 'https://www.zomato.com/praha/fiesta-dejvice-praha-6/menu', '16505937'),
                ('Guston', 'https://www.zomato.com/praha/guston-žižkov-praha-3/menu', '16522019'),
                ('Styl & Interier', 'https://www.zomato.com/praha/styl-interier-nové-město-praha-1/menu', '16521792'),
                ('Café Lounge', 'https://www.zomato.com/praha/café-lounge-malá-strana-praha-5/menu', '16509748'),
                ('Pivovar Hostivar', 'https://www.zomato.com/praha/pivovar-hostivar-horní-měcholupy-praha-10/menu',
                 '16506778'),
                ('Charleston', 'https://www.zomato.com/praha/charleston-karlín-praha-8/menu', '16506909'),
                ('Česká hospůdka Na Radnici',
                 'https://www.zomato.com/praha/česká-hospůdka-na-radnici-vysočany-praha-9/menu', '16507416'),
                ('Novoměstský pivovar', 'https://www.zomato.com/praha/novoměstský-pivovar-nové-město-praha-1/menu',
                 '16505916'),
                ('Salaš U Staré cesty', 'https://www.zomato.com/praha/salaš-u-staré-cesty-střešovice-praha-6/menu',
                 '17837639'),
                ('Nota Bene', 'https://www.zomato.com/praha/nota-bene-vinohrady-praha-2/menu', '16507130'),
                ('Modrá Zahrada', 'https://www.zomato.com/praha/modrá-zahrada-staré-město-praha-1/menu', '16505960'),
                ('500 restaurant', 'https://www.zomato.com/praha/500-restaurant-hradčany-praha-6/menu', '16507125'),
                ('Na Kačabce - Putyka', 'https://www.zomato.com/praha/na-kačabce-putyka-hostivař-praha-10/menu',
                 '16520654'),
                ('Steakhouse Stará Škola', 'https://www.zomato.com/praha/steakhouse-stará-škola-zbraslav-praha-5/menu',
                 '16507260'),
                ('Crystal Bar & Restaurant', 'https://www.zomato.com/crystalprague/menu', '16506812'),
                ('Café Neustadt', 'https://www.zomato.com/praha/café-neustadt-nové-město-praha-2/menu', '16507113'),
                ('U Balouna', 'https://www.zomato.com/praha/u-balouna-nové-město-praha-1/menu', '16506176'),
                ('Sweet & Pepper Days', 'https://www.zomato.com/praha/sweet-pepper-days-vinohrady-praha-2/menu',
                 '16507029'),
                ('U Sudů', 'https://www.zomato.com/praha/u-sudů-strašnice-praha-10/menu', '16506980'),
                ('Kozlovna Lidická', 'https://www.zomato.com/praha/kozlovna-lidická-smíchov-praha-5/menu', '16508973'),
                ('Garage', 'https://www.zomato.com/praha/garage-karlín-praha-8/menu', '17852238'),
                ('Indian Jewel', 'https://www.zomato.com/praha/indian-jewel-staré-město-praha-1/menu', '16506888'),
                ('Maitrea', 'https://www.zomato.com/praha/maitrea-1-staré-město-praha-1/menu', '16517165'),
                ('Mamy', 'https://www.zomato.com/mamy/menu', '16506687'),
                ('Na Kopci', 'https://www.zomato.com/praha/na-kopci-smíchov-praha-5/menu', '16516755'),
                ('Restaurant Esprit - Holiday Inn Prague Congress Centre', 'https://www.zomato.com/ESPRIT/menu',
                 '16506139'),
                ('Indian by Nature', 'https://www.zomato.com/praha/indian-by-nature-karlín-praha-8/menu', '16506583'),
                ('Gourmet Pauza', 'https://www.zomato.com/praha/gourmet-pauza-smíchov-praha-5/menu', '17852225'),
                ('Bistro Proti proudu', 'https://www.zomato.com/praha/bistro-proti-proudu-karlín-praha-8/menu',
                 '16521753'),
                ('Krystal Bistro', 'https://www.zomato.com/praha/krystal-bistro-karlín-praha-8/menu', '16506262'),
                ('Kofein', 'https://www.zomato.com/praha/kofein-vinohrady-praha-3/menu', '16521516'),
                ('Café Colore', 'https://www.zomato.com/praha/café-colore-1-nové-město-praha-1/menu', '16506173'),
                ('Café NoD', 'https://www.zomato.com/praha/café-nod-staré-město-praha-1/menu', '16507445'),
                ('Engawa sushi bar', 'https://www.zomato.com/praha/engawa-sushi-bar-nové-město-praha-1/menu',
                 '17978831'),
                ('Cafe Frida', 'https://www.zomato.com/praha/cafe-frida-karlín-praha-8/menu', '16507051'),
                ('mamacoffee', 'https://www.zomato.com/praha/mamacoffee-nové-město-praha-1/menu', '16506094'),
                ('Restaurace Alcron - Radisson Blu Alcron Hotel',
                 'https://www.zomato.com/praha/restaurace-alcron-radisson-blu-alcron-hotel-nové-město-praha-1/menu',
                 '16517185'),
                ('Levitate Restaurant', 'https://www.zomato.com/praha/levitate-restaurant-nové-město-praha-1/menu',
                 '18549913'),
                ('Svatá Klára', 'https://www.zomato.com/praha/svatá-klára-troja-praha-7/menu', '16516425'),
                ('Bellevue', 'https://www.zomato.com/praha/bellevue-staré-město-praha-1/menu', '16511730'),
                ('Kalina cuisine & vins', 'https://www.zomato.com/praha/kalina-cuisine-vins-staré-město-praha-1/menu',
                 '16518242'),
                ('Salabka', 'https://www.zomato.com/praha/salabka-troja-praha-7/menu', '16516450'),
                ('Artista - Le Palais', 'https://www.zomato.com/praha/artista-le-palais-vinohrady-praha-2/menu',
                 '16506187'),
                ('Zvonice', 'https://www.zomato.com/praha/zvonice-nové-město-praha-1/menu', '16507598'),
                ('Grand Cru', 'https://www.zomato.com/praha/grand-cru-nové-město-praha-1/menu', '16507519'),
                ('SaSaZu', 'https://www.zomato.com/praha/sasazu-holešovice-praha-7/menu', '16508860'),
                ('Divinis', 'https://www.zomato.com/praha/divinis-staré-město-praha-1/menu', '16506960'),
                ('Buddha Bar', 'https://www.zomato.com/praha/buddha-bar-staré-město-praha-1/menu', '16507413'),
                ('La Finestra in Cucina', 'https://www.zomato.com/praha/la-finestra-in-cucina-staré-město-praha-1/menu',
                 '16515923'),
                (
                    'Francouzská restaurace Art Nouveau', 'https://www.zomato.com/francouzska-restaurace/menu',
                    '16508483'),
                ('Spices Restaurant and Bar - Mandarin Oriental Prague',
                 'https://www.zomato.com/praha/spices-restaurant-and-bar-mandarin-oriental-prague-malá-strana-praha-1/menu',
                 '16514160'),
                ('La Rotonde - Radisson Blu Alcron Hotel',
                 'https://www.zomato.com/praha/la-rotonde-radisson-blu-alcron-hotel-nové-město-praha-1/menu',
                 '16517239'),
                ('Gourmet restaurant - Hotel Hoffmeister',
                 'https://www.zomato.com/praha/gourmet-restaurant-hotelu-hoffmeister-hradčany-praha-1/menu',
                 '16506431'),
                ('Aromi', 'https://www.zomato.com/praha/aromi-1-vinohrady-praha-2/menu', '18156332'),
                ('Hergetova Cihelna', 'https://www.zomato.com/praha/hergetova-cihelna-malá-strana-praha-1/menu',
                 '16507441'),
                ('Augustine Restaurant', 'https://www.zomato.com/praha/augustine-restaurant-malá-strana-praha-1/menu',
                 '16510720'),
                ('Be Bop Bar - Radisson Blu Alcron Hotel',
                 'https://www.zomato.com/praha/be-bop-bar-radisson-blu-alcron-hotel-nové-město-praha-1/menu',
                 '16517089'),
                ('El Emir', 'https://www.zomato.com/praha/el-emir-nové-město-praha-1/menu', '16506427'),
                ('Portfolio restaurant', 'https://www.zomato.com/portfoliorestaurant/menu', '18311827'),
                ('Restaurace Hradčany - Hotel Savoy',
                 'https://www.zomato.com/praha/restaurace-hradčany-hotel-savoy-hradčany-praha-1/menu', '16507555'),
                ('The Sushi Bar', 'https://www.zomato.com/praha/the-sushi-bar-malá-strana-praha-5/menu', '16510998'),
                ('U Malířů 1543', 'https://www.zomato.com/praha/u-malířů-1543-malá-strana-praha-1/menu', '16511961'),
                ('Pálffy Palác', 'https://www.zomato.com/praha/pálffy-palác-malá-strana-praha-1/menu', '16508383'),
                ('Cloud 9 Sky Bar & Lounge - Hilton Prague Hotel',
                 'https://www.zomato.com/praha/cloud-9-sky-bar-lounge-hilton-prague-hotel-karlín-praha-8/menu',
                 '16510868'),
                ('Miyabi', 'https://www.zomato.com/praha/miyabi-nové-město-praha-1/menu', '16507296'),
                ('Ginger & Fred', 'https://www.zomato.com/praha/ginger-fred-nové-město-praha-2/menu', '16511343'),
                ('El Toro negro', 'https://www.zomato.com/praha/el-toro-negro-staré-město-praha-1/menu', '16510064'),
                ('Franz Josef Restaurant - Grand Hotel Bohemia',
                 'https://www.zomato.com/praha/franz-josef-restaurant-grand-hotel-bohemia-staré-město-praha-1/menu',
                 '16509388'),
                ('Asian Temple', 'https://www.zomato.com/praha/asian-temple-staré-město-praha-1/menu', '18163248'),
                ('Chateau St. Havel', 'https://www.zomato.com/praha/chateau-st-havel-1-krč-praha-4/menu', '16516941'),
                ('New York Café - Boscolo Prague',
                 'https://www.zomato.com/praha/new-york-café-boscolo-prague-nové-město-praha-1/menu', '16510273'),
                ('VINOdiVINO', 'https://www.zomato.com/praha/vinodivino-staré-město-praha-1/menu', '16506304'),
                ('ART&FOOD Had', 'https://www.zomato.com/ARTFOODHad/menu', '16514146'),
                ('Pekařství a cukrářství Helena Šmejkalová',
                 'https://www.zomato.com/praha/pekařství-a-cukrářství-helena-šmejkalová-vršovice-praha-10/menu',
                 '16516569'),
                ('Café Savoy', 'https://www.zomato.com/praha/café-savoy-malá-strana-praha-5/menu', '16511100'),
                ('Palanda', 'https://www.zomato.com/praha/palanda-nové-město-praha-1/menu', '16507043'),
                ('Delmart', 'https://www.zomato.com/praha/delmart-smíchov-praha-5/menu', '16521798'),
                ('Vinohradský parlament', 'https://www.zomato.com/praha/vinohradský-parlament-vinohrady-praha-2/menu',
                 '16510163'),
                ('Bejzment', 'https://www.zomato.com/praha/bejzment-smíchov-praha-5/menu', '16508716'),
                ('Monolok', 'https://www.zomato.com/praha/monolok-vinohrady-praha-2/menu', '16521454'),
                ('The Farm', 'https://www.zomato.com/praha/the-farm-bubeneč-praha-7/menu', '16509642'),
                ('IF Café', 'https://www.zomato.com/praha/if-café-1-vinohrady-praha-2/menu', '16521743'),
                ('Můj šálek kávy', 'https://www.zomato.com/praha/můj-šálek-kávy-karlín-praha-8/menu', '16509186'),
                ('Cafe ~ cafe', 'https://www.zomato.com/praha/cafe-cafe-staré-město-praha-1/menu', '16510131'),
                ('Bruxx', 'https://www.zomato.com/praha/bruxx-vinohrady-praha-2/menu', '16510160'),
                ('Angelato', 'https://www.zomato.com/praha/angelato-malá-strana-praha-1/menu', '16511989'),
                ('Hard Rock Cafe', 'https://www.zomato.com/hardrock/menu', '16510644'),
                ('Kandelábr', 'https://www.zomato.com/praha/kandelábr-nusle-praha-4/menu', '16506739'),
                ('Potrefená husa', 'https://www.zomato.com/praha/potrefená-husa-1-nové-město-praha-1/menu', '16511008'),
                ('Místo', 'https://www.zomato.com/praha/místo-dejvice-praha-6/menu', '17984486'),
                ('Barabizna', 'https://www.zomato.com/praha/barabizna-zbraslav-praha-5/menu', '16519949'),
                ('Ordr', 'https://www.zomato.com/praha/ordr-nové-město-praha-1/menu', '18355488'),
                ('Želva beers & burgers', 'https://www.zomato.com/praha/želva-beers-burgers-žižkov-praha-3/menu',
                 '18275803'),
                ('La Bohème Café', 'https://www.zomato.com/praha/la-bohème-café-vinohrady-praha-2/menu', '16510432'),
                ('Stereo', 'https://www.zomato.com/praha/stereo-bubeneč-praha-7/menu', '16507141'),
                ('Modrý zub', 'https://www.zomato.com/praha/modrý-zub-smíchov-praha-5/menu', '16521678'),
                ('Puro Gelato', 'https://www.zomato.com/praha/puro-gelato-nové-město-praha-2/menu', '16521994'),
                ('Nebe Cocktail & Music Club',
                 'https://www.zomato.com/praha/nebe-cocktail-music-club-nové-město-praha-1/menu', '16516184'),
                ('James Dean Prague Restaurant', 'https://www.zomato.com/praha/james-dean-staré-město-praha-1/menu',
                 '16517681'),
                ('Eska', 'https://www.zomato.com/praha/eska-karlín-praha-8/menu', '18163255'),
                ('Yam Yam', 'https://www.zomato.com/praha/yam-yam-nusle-praha-4/menu', '16508845'),
                ('U Fleků', 'https://www.zomato.com/praha/u-fleků-nové-město-praha-1/menu', '16507333'),
                ('Angelato', 'https://www.zomato.com/praha/angelato-staré-město-praha-1/menu', '16510167'),
                (
                    'Lokál U Zavadilů', 'https://www.zomato.com/praha/lokál-u-zavadilů-kunratice-praha-4/menu',
                    '16506696'),
                ('Sicily café', 'https://www.zomato.com/praha/sicily-café-nové-město-praha-1/menu', '16506438'),
                ('The Tavern', 'https://www.zomato.com/praha/the-tavern-vinohrady-praha-2/menu', '16508596'),
                ('Pivovar Národní', 'https://www.zomato.com/praha/pivovar-národní-nové-město-praha-1/menu', '17830788'),
                ('Kavárna Slavia', 'https://www.zomato.com/praha/kavárna-slavia-staré-město-praha-1/menu', '16510882'),
                ('Bombay Express', 'https://www.zomato.com/praha/bombay-express-žižkov-praha-3/menu', '16521752'))

        for restaurant in data:
            name = restaurant[0]
            menu_url = restaurant[1]
            zomato_id = restaurant[2]

            restaurant_model = Restaurant(name=name, menu_url=menu_url)
            restaurant_model.save()

            scrapper_config = RestaurantScraperConfig(restaurant=restaurant_model, menu_parser='daily_menu.Zomato',
                                                      parser_parameters=zomato_id, next_visit=datetime.today(),
                                                      next_visit_interval=1
                                                      )

            scrapper_config.save()

