# Generated by Django 2.1.4 on 2019-05-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_dailymenu_classification_in_progress'),
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantScrapperConfig',
            new_name='RestaurantScraperConfig',
        ),
    ]
